### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mkauzlar** [CoMPaTech/plugin-theme_auto_day_night#1]
if I follow the install procedure of this plugin I get:
Internal Error: Unable to load this plugin class \Kanboard\Plugin\Theme_auto_night_day\Plugin

**Comment by CoMPaTech** [comment]
Sorry, as per commit of the readme, the naming matters (and the readme had an incorrect capital mentioned).

If you rename the directory to `theme_auto_day_night` it should work!

**Comment by mkauzlar** [comment]
that worked thanks. The plugin loads now and is listed in the plugins menu.

The next issue is that I don't see any interface changes. My timezone is set correctly and is 21h now here so I would expect the theme to change to dark, right?
Should  I open another issue for this?

**Comment by CoMPaTech** [comment]
Yeah, just spotted that ... somehow it's still looking for things with the capital, spare me a minute, trying to get it working. You should get settings in 'integrations' but somehow they don't show up.

**Comment by CoMPaTech** [comment]
Taking some time ... Templates/layout/head.php could just take in 

```
use Kanboard\Model\Config;
$configModel = new Config($this->container);
```

To get the configuration settings set in 'integrations.php' But for some reason in the last release this isn't working anylonger. Looking into @fguillot code what is changed and/or what I can use

**Comment by CoMPaTech** [comment]
@mkauzlar Could you retry, also changed back the naming (so with capital T) again until 1.0.28 is finished (as that seems to provide a solution for naming).

**Comment by mkauzlar** [comment]
Seems to be working ok now
