### ISSUE TITLE
Yet not working

### ISSUE THREAD

**Issue by idchlife** [CoMPaTech/plugin-theme_auto_day_night#2]
Internal Error: Unable to load this plugin class \Kanboard\Plugin\Template\Plugin

**Comment by CoMPaTech** [comment]
On which version, 1.0.32?

**Comment by CoMPaTech** [comment]
(And during (new) install or upgrade)

**Comment by idchlife** [comment]
@CoMPaTech new install, 1.0.32 yes!

**Comment by CoMPaTech** [comment]
Ack, looking into it

**Comment by idchlife** [comment]
@CoMPaTech it was my mistake. I did install it wrongly! Everything is fine now, thank you!

**Comment by CoMPaTech** [comment]
Ok then, enjoy!
